AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policy forFile Gateway S3 Accesson'

Resources:
  S3AccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: FilegatewayAccessRep
      Description: 'Policy to provide access permissions for S3 related actions.'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:AbortMultipartUpload"
              - "s3:DeleteObject"
              - "s3:DeleteObjectVersion"
              - "s3:GetAccelerateConfiguration"
              - "s3:GetBucketLocation"
              - "s3:GetBucketVersioning"
              - "s3:GetObject"
              - "s3:GetObjectAcl"
              - "s3:GetObjectVersion"
              - "s3:ListBucket"
              - "s3:ListBucketVersions"
              - "s3:ListBucketMultipartUploads"
              - "s3:ListMultipartUploadParts"
              - "s3:PutObject"
              - "s3:PutObjectAcl"
            Resource: "*"
